# Generated by Django 4.1.7 on 2023-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
