# Generated by Django 4.1.7 on 2023-04-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0002_boo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boo',
            old_name='email',
            new_name='Address',
        ),
    ]
